ren Commodore-CDTV.png 					  "Commodore CDTV.png" 
ren Commodore-Amiga.png                   "Commodore Amiga.png"
ren Commodore-Amiga-CD32.png              "Commodore Amiga CD32.png"
ren Commodore-64.png                      "Commodore 64.png"
ren Commodore-16.png                      "Commodore 16.png"
ren Coleco-Colecovision.png               "Coleco Colecovision.png"
ren Cave.png                              "Cave.png"
ren Casio-PV-2000.png                     "Casio PV 2000.png"
ren Casio-PV-1000.png                     "Casio PV 1000.png"
ren Capcom.png                            "Capcom.png"
ren Capcom-CPSIII.png                     "Capcom CPSIII.png"
ren Capcom-(3).png                        "Capcom (3).png"
ren Capcom-(2).png                        "Capcom (2).png"
ren Big-Fish-Games.png                    "Big Fish Games.png"
ren Bandai-Wonderswan.png                 "Bandai Wonderswan.png"
ren Bandai-WonderSwan-Color.png           "Bandai WonderSwan Color.png"
ren Bally-Astrocade.png                   "Bally Astrocade.png"
ren Attack-of-the-Clones.png              "Attack of the Clones.png"
ren Atari-XE.png                          "Atari XE.png"
ren Atari-ST.png                          "Atari ST.png"
ren Atari-Lynx.png                        "Atari Lynx.png"
ren Atari-Jaguar.png                      "Atari Jaguar.png"
ren Atari-Jaguar-CD.png                   "Atari Jaguar CD.png"
ren Atari-7800.png                        "Atari 7800.png"
ren Atari-5200.png                        "Atari 5200.png"
ren Atari-2600.png                        "Atari 2600.png"
ren Atari-8-bit.png                       "Atari 8 bit.png"
ren Apple-II.png                          "Apple II.png"
ren APF.png                               "APF.png"
ren Amstrad-GX4000.png                    "Amstrad GX4000.png"
ren Amstrad-CPC.png                       "Amstrad CPC.png"
ren American-Laser-Games.png              "American Laser Games.png"
ren American-Laser-Games-(2).png          "American Laser Games (2).png"
ren AAE.png                               "AAE.png"
ren Zinc.png                              "Zinc.png"
ren XBMC.png                              "XBMC.png"
ren WoW-Action-Max.png                    "WoW Action Max.png"
ren Watara-Supervision.png                "Watara Supervision.png"
ren VTech-Creativision.png                "VTech Creativision.png"
ren Visual-Pinball.png                    "Visual Pinball.png"
ren Triforce.png                          "Triforce.png"
ren Touhou.png                            "Touhou.png"
ren Tiger-Game.png                        "Tiger Game.png"
ren TI-99-4A.png                          "TI 99 4A.png"
ren Taito-Type-X2.png                     "Taito Type X2.png"
ren Taito-Type-X.png                      "Taito Type X.png"
ren Super-Nintendo-Entertainment-System.png "Super Nintendo Entertainment System.png
ren Super-Cassette-Vision.png             "Super Cassette Vision.png"
ren Stepmania.png                         "Stepmania.png"
ren Steam.png                             "Steam.png"
ren Sony-Playstation.png                  "Sony Playstation.png"
ren Sony-Playstation-Portable.png         "Sony Playstation Portable.png"
ren Sony-Playstation-2.png                "Sony Playstation 2.png"
ren SNK-Neo-Geo-Pocket.png                "SNK Neo Geo Pocket.png"
ren SNK-Neo-Geo-Pocket-Color.png          "SNK Neo Geo Pocket Color.png"
ren SNK-Neo-Geo-CD.png                    "SNK Neo Geo CD.png"
ren SNK-Neo-Geo-AES.png                   "SNK Neo Geo AES.png"
ren Sinclair-ZX-Spectrum.png              "Sinclair ZX Spectrum.png"
ren Sharp-X68000.png                      "Sharp X68000.png"
ren Sega-ST-V.png                         "Sega ST V.png"
ren Sega-SG-1000.png                      "Sega SG 1000.png"
ren Sega-Saturn.png                       "Sega Saturn.png"
ren Sega-Naomi.png                        "Sega Naomi.png"
ren Sega-Model-3.png                      "Sega Model 3.png"
ren Sega-Model-2.png                      "Sega Model 2.png"
ren Sega-Master-System.png                "Sega Master System.png"
ren Sega-Genesis.png                      "Sega Genesis.png"
ren Sega-Genesis-(2).png                  "Sega Genesis (2).png"
ren Sega-Game-Gear.png                    "Sega Game Gear.png"
ren Sega-Dreamcast.png                    "Sega Dreamcast.png"
ren Sega-Dreamcast-(2).png                "Sega Dreamcast (2).png"
ren Sega-CD.png                           "Sega CD.png"
ren Sega-CD-(2).png                       "Sega CD (2).png"
ren Sega-32X.png                          "Sega 32X.png"
ren ScummVM.png                           "ScummVM.png"
ren Sammy-Atomiswave.png                  "Sammy Atomiswave.png"
ren RCA-Studio-II.png                     "RCA Studio II.png"
ren PopCap.png                            "PopCap.png"
ren Pokemon-Mini.png                      "Pokemon Mini.png"
ren Philips-VG5000.png                    "Philips VG5000.png"
ren Philips-CD-i.png                      "Philips CD i.png"
ren PC-Games.png                          "PC Games.png"
ren PC-Games-(3).png                      "PC Games (3).png"
ren PC-Games-(2).png                      "PC Games (2).png"
ren Panasonic-3DO.png                     "Panasonic 3DO.png"
ren OpenBOR.png                           "OpenBOR.png"
ren Nuon.png                              "Nuon.png"
ren Nintendo-Wii.png                      "Nintendo Wii.png"
ren Nintendo-Virtual-Boy.png              "Nintendo Virtual Boy.png"
ren Nintendo-Super-Famicom.png            "Nintendo Super Famicom.png"
ren Nintendo-Homebrew.png                 "Nintendo Homebrew.png"
ren Nintendo-Gamecube.png                 "Nintendo Gamecube.png"
ren Nintendo-Gameboy-Advance-(2).png      "Nintendo Gameboy Advance (2).png"
ren Nintendo-Game-Boy.png                 "Nintendo Game Boy.png"
ren Nintendo-Game-Boy-Color.png           "Nintendo Game Boy Color.png"
ren Nintendo-Game-Boy-Advance.png         "Nintendo Game Boy Advance.png"
ren Nintendo-Game-&-Watch.png             "Nintendo Game & Watch.png"
ren Nintendo-Famicom.png                  "Nintendo Famicom.png"
ren Nintendo-Famicom-Disk-System.png      "Nintendo Famicom Disk System.png"
ren Nintendo-Entertainment-System.png     "Nintendo Entertainment System.png"
ren Nintendo-DS.png                       "Nintendo DS.png"
ren Nintendo-Arcade-System.png            "Nintendo Arcade System.png"
ren Nintendo-64.png                       "Nintendo 64.png"
ren NeoGeo-AES.png                        "NeoGeo AES.png"
ren NEC-TurboGrafx-CD.png                 "NEC TurboGrafx CD.png"
ren NEC-TurboGrafx-16.png                 "NEC TurboGrafx 16.png"
ren Nec-Turbo-Duo.png                     "Nec Turbo Duo.png"
ren NEC-SuperGrafx.png                    "NEC SuperGrafx.png"
ren NEC-PC-FX.png                         "NEC PC FX.png"
ren NEC-PC-Engine.png                     "NEC PC Engine.png"
ren NEC-PC-Engine-CD.png                  "NEC PC Engine CD.png"
ren MUGEN.png                             "MUGEN.png"
ren MSDOS.png                             "MSDOS.png"
ren Movies.png                            "Movies.png"
ren Misfit-Mame.png                       "Misfit Mame.png"
ren Microsoft-MSX2.png                    "Microsoft MSX2.png"
ren Microsoft-MSX.png                     "Microsoft MSX.png"
ren Media-Browser.png                     "Media Browser.png"
ren Media-Browser-(2).png                 "Media Browser (2).png"
ren Mattel-Intellivision.png              "Mattel Intellivision.png"
ren Mattel-Aquarius.png                   "Mattel Aquarius.png"
ren MAME.png                              "MAME.png"
ren MAME-(2).png                          "MAME (2).png"
ren Magnavox-Odyssey.png                  "Magnavox Odyssey.png"
ren Magnavox-Odyssey-2.png                "Magnavox Odyssey 2.png"
ren Jukebox.png                           "Jukebox.png"
ren HBMame.png                            "HBMame.png"
ren GOG.png                               "GOG.png"
ren GCE-Vectrex.png                       "GCE Vectrex.png"
ren GamePark-32.png                       "GamePark 32.png"
ren Future-Pinball.png                    "Future Pinball.png"
ren Fujitsu-FM-Towns.png                  "Fujitsu FM Towns.png"
ren Fruit-Machines.png                    "Fruit Machines.png"
ren Frets-on-Fire.png                     "Frets on Fire.png"
ren Flash-Games.png                       "Flash Games.png"
ren Flash-Games-(3).png                   "Flash Games (3).png"
ren Flash-Games-(2).png                   "Flash Games (2).png"
ren Fairchild-Channel-F.png               "Fairchild Channel F.png"
ren Entex-Adventure-Vision.png            "Entex Adventure Vision.png"
ren Emerson-Arcadia-2001.png              "Emerson Arcadia 2001.png"
ren Doujin-Games.png                      "Doujin Games.png"
ren DICE.png                              "DICE.png"
ren Daphne.png                            "Daphne.png"
ren Daphne-(2).png                        "Daphne (2).png"
ren Creatonic-Mega-Duck.png               "Creatonic Mega Duck.png"
ren CommodoreVIC-20.png                   "CommodoreVIC 20.png"
ren Commodore-MAX.png                     "Commodore MAX.png"
